FROM postgres:10.4

LABEL MAINTAINER Ashwin Rayaprolu <ashwin.rayaprolu@gmail.com>

# Install prerequisites
RUN apt-get update && apt-get install -y curl

RUN mkdir /var/temp

## Download from nexus to /var/tmp and remove COPY command
#RUN (cd /var/temp/ && curl -O http://nexus.cicd.sv2.247-inc.net/nexus/repository/packages/answers/db/db.tar.gz)
COPY db.tar.gz /var/temp/

RUN (cd /var/temp/ && tar -zxvf db.tar.gz && cp /var/temp/bchydro.sql /docker-entrypoint-initdb.d/2_db.sql)

EXPOSE  5432
