version: '3'
services:
  app:

    build:
      context: ./
      dockerfile: pytest/Dockerfile
    container_name: app
    volumes:
    - ./:/src
    stdin_open: true
    tty: true
    entrypoint: /bin/bash
    environment:
      - PYTHONPATH=./src