version: '3.2'

services:
    posthog_db:
        container_name: posthog_db
        environment:
            POSTGRES_DB: posthog
            POSTGRES_PASSWORD: posthog
            POSTGRES_USER: posthog
        image: postgres:alpine
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
          back-tier:
             ipv4_address: 10.10.0.40            
            
            
    posthog_redis:
        container_name: posthog_redis
        image: redis:alpine
        networks:
          back-tier:
             ipv4_address: 10.10.0.41
             
                     
    posthog_web:
        container_name: posthog_web
        depends_on:
            - posthog_db
            - posthog_redis
        environment:
            DATABASE_URL: postgres://posthog:posthog@posthog_db:5432/posthog
            IS_DOCKER: 'true'
            REDIS_URL: redis://posthog_redis:6379/
            SECRET_KEY: sdfdfsfsfs3453
            DISABLE_SECURE_SSL_REDIRECT: 'true'
            IS_BEHIND_PROXY: 'true'            
        image: posthog/posthog:latest
        ports:
            - 8000:8000
        networks:
          back-tier:
             ipv4_address: 10.10.0.42            
            
            
volumes:
    postgres-data:
    
    

networks:
  front-tier:
    driver: bridge
    ipam:
      config:
      - subnet: "10.9.0.0/16"  
  back-tier:
    driver: bridge
    ipam:
      config:
      - subnet: "10.10.0.0/16"  
    
    
