version: '3.2'
services:
 
 



  # Local Mail Configurations        
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    command: ["-smtp-bind-addr", "0.0.0.0:25"]
    user: root
    expose:
      - 25
      - 8025
    environment:
      HOST_PORT_MAILHOG: 25  
    ports:
      #- 1025:25
      - 25
      - 8025:8025
    healthcheck:
      test: echo | telnet 127.0.0.1 25  
    networks:
      front-tier:
         ipv4_address: 10.9.0.6
      back-tier:
         ipv4_address: 10.10.0.6
      
        

    
volumes:
  db-data:



networks:
  front-tier:
    driver: bridge
    ipam:
      config:
      - subnet: "10.9.0.0/16"  
  back-tier:
    driver: bridge
    ipam:
      config:
      - subnet: "10.10.0.0/16"  
    
